Probando el try en pyhton